input_boolean: !include_dir_merge_named input_booleans
default_config:
mqtt:
  sensor:
    - name: "Diebstahlsensor Aktion"
      unique_id: diebstahlsensor_action
      state_topic: "zigbee2mqtt/Diebstahlsensor"
      value_template: "{{ value_json.action | default('unknown') }}"
      json_attributes_topic: "zigbee2mqtt/Diebstahlsensor"
    - name: "Diebstahlsensor Batterie"
      unique_id: diebstahlsensor_battery
      state_topic: "zigbee2mqtt/Diebstahlsensor"
      value_template: "{{ value_json.battery }}"
      unit_of_measurement: "%"
      device_class: battery
      state_class: measurement
  binary_sensor:
    - name: "Tasche Bewegung"
      unique_id: tasche_bewegung_mqtt
      state_topic: "zigbee2mqtt/Diebstahlsensor"
      device_class: motion
      off_delay: 120
      value_template: >
        {% if value_json.action | default('') in ['movement', 'vibration'] %}
          ON
        {% else %}
          OFF
        {% endif %}
      payload_on: "ON"
      payload_off: "OFF"
command_line: !include_dir_merge_list command_lines
rest: !include_dir_merge_list rest
utility_meter: !include utility_meters.yaml
frontend:
  themes: !include_dir_merge_named themes
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
lovelace:
    mode: storage
    dashboards:
        ipad-dashboard:
            mode: yaml
            title: IPad
            icon: mdi:tablet
            show_in_sidebar: true
            filename: dashboard/ipad-dashboard.yaml
        iphone-dashboard:
            mode: yaml
            title: iPhone
            icon: mdi:phone
            show_in_sidebar: true
            filename: dashboard/iphone-dashboard.yaml
template: !include_dir_merge_list templates
