input_boolean: !include_dir_merge_named input_booleans
default_config:
mqtt:
  sensor:
    - name: "Office Theft Sensor Action"
      unique_id: office_theft_sensor_action
      state_topic: "zigbee2mqtt/office Theft Sensor"
      value_template: "{{ value_json.action | default('unknown') }}"
      json_attributes_topic: "zigbee2mqtt/office Theft Sensor"
  binary_sensor:
    - name: "Office Theft Sensor Movement"
      unique_id: office_theft_sensor_movement_mqtt
      state_topic: "zigbee2mqtt/office Theft Sensor"
      device_class: motion
      off_delay: 120
      payload_on: "ON"
      value_template: >
        {% if value_json.action | default('') in ['movement', 'vibration'] %}
          ON
        {% endif %}
command_line: !include_dir_merge_list command_lines
rest: !include_dir_merge_list rest
utility_meter: !include utility_meters.yaml
frontend:
  themes: !include_dir_merge_named themes
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list templates
