- alias: WC-Licht bei Präsenz und Dunkelheit
  id: wc_licht_praesenz_dunkelheit
  description: Schaltet das WC-Licht bei Präsenz ein, wenn es dunkel ist, und bei Abwesenheit wieder aus.
  triggers:
    - trigger: state
      entity_id: binary_sensor.guest_wc_presence_sensor_presence
      to: "on"
      id: presence_on
    - trigger: state
      entity_id: binary_sensor.guest_wc_presence_sensor_presence
      to: "off"
      for:
        seconds: 30
      id: presence_off
  conditions: []
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: presence_on
            - condition: numeric_state
              entity_id: sensor.guest_wc_presence_sensor_illuminance
              below: 150
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.powder_room_wc
        - conditions:
            - condition: trigger
              id: presence_off
          sequence:
            - action: light.turn_off
              target:
                entity_id: light.powder_room_wc
  mode: restart