- alias: "Mywellness Kurs IDs vorbereiten"
  trigger:
    - platform: time
      at: "17:00:00"
  action:
    - service: shell_command.mywellness_prepare
  mode: single

- alias: "MyWellness Booking System"
  trigger:
    - platform: time
      at: "20:59:58"
  action:
    - service: shell_command.mywellness_book
  mode: single